# Generated by Django 5.2.5 on 2026-08-21 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantsettings',
            name='auto_update_exchange_rate',
            field=models.BooleanField(default=True, help_text='Automatically refresh the exchange rate when the API integration is enabled.'),
        ),
        migrations.AddField(
            model_name='restaurantsettings',
            name='base_currency',
            field=models.CharField(choices=[('NGN', 'Nigerian Naira (₦)'), ('USD', 'US Dollar ($)'), ('EUR', 'Euro (€)'), ('GBP', 'British Pound (£)')], default='NGN', help_text='Currency used for actual restaurant pricing and orders.', max_length=3),
        ),
        migrations.AddField(
            model_name='restaurantsettings',
            name='display_currency',
            field=models.CharField(choices=[('NGN', 'Nigerian Naira (₦)'), ('USD', 'US Dollar ($)'), ('EUR', 'Euro (€)'), ('GBP', 'British Pound (£)')], default='NGN', help_text='Currency used when displaying converted prices to customers.', max_length=3),
        ),
        migrations.AddField(
            model_name='restaurantsettings',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Number of display-currency units for 1 base-currency unit.', max_digits=12),
        ),
        migrations.AddField(
            model_name='restaurantsettings',
            name='exchange_rate_provider',
            field=models.CharField(default='CBN / Frankfurter', help_text='Source used for the exchange rate.', max_length=100),
        ),
        migrations.AddField(
            model_name='restaurantsettings',
            name='exchange_rate_updated_at',
            field=models.DateTimeField(blank=True, help_text='When the current exchange rate was last updated.', null=True),
        ),
        migrations.AlterField(
            model_name='restaurantsettings',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Enter percentage, e.g. 7.50 for 7.5%.', max_digits=5),
        ),
    ]
