# Generated by Django 5.2.17 on 2026-08-09 21:16

import accounts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dashboard_enabled', models.BooleanField(default=False, help_text='Can this staff member open the custom Dashboard at all?')),
                ('admin_panel_enabled', models.BooleanField(default=False, help_text='Can this staff member open Django Admin at /admin/ at all?')),
                ('nav_dashboard_to_admin', models.BooleanField(default=False, help_text="Show the 'Admin Panel' button inside the Dashboard.")),
                ('nav_admin_to_dashboard', models.BooleanField(default=False, help_text="Show the 'Back to Dashboard' link inside Django Admin.")),
                ('dashboard_sections', models.JSONField(default=accounts.models._default_sections, help_text='Per-module ON/OFF for the Dashboard sidebar.')),
                ('admin_sections', models.JSONField(default=accounts.models._default_sections, help_text='Per-module ON/OFF for Django Admin.')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_access', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Staff Access',
                'verbose_name_plural': 'Staff Access',
            },
        ),
    ]
