# Generated by Django 5.2.17 on 2026-08-30 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auditaction_recovery_choices'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountrecoveryrequest',
            options={'verbose_name': 'Account Recovery Request', 'verbose_name_plural': 'Account Recovery Requests'},
        ),
        migrations.AlterModelOptions(
            name='auditlogentry',
            options={'verbose_name': 'Audit Log Entry', 'verbose_name_plural': 'Audit Log Entries'},
        ),
        migrations.AlterModelOptions(
            name='backupcode',
            options={'verbose_name': 'Backup Code', 'verbose_name_plural': 'Backup Codes'},
        ),
    ]
